name: 🙋‍♂️ Ask a question
description: Tell us what's on your mind
title: "[Question]: "
labels: ["Question"]
body:
  - type: markdown
    attributes:
      value: |
        Having issues integrating this API library?
  - type: textarea
    id: question
    attributes:
      label: How can we help?
      description: Specific question regarding integrating this API library.
      placeholder: How do I...?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OneSignal/api/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
